language: node_js
node_js:
  - "8"
branches:
  only: master
script:
  - npm run build
after_script:
  - cd dist
  - git init
  - git config user.name "Dafrok"
  - git config user.email "o.o@mug.dog"
  - git add .
  - git commit -m "Travis build"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/Dafrok/vue-baidu-map.git" master:gh-pages